apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -ssh-demo

resources:
- ../base

images:
- name: quay.io/confidential-containers/runtime-payload
  newTag: kata-containers-ssh-demo-v0.2.0
- name: quay.io/confidential-containers/container-engine-for-cc-payload
  newTag: 1def978fdf6b0cb2383d43970c3dc484df3cad54

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClassNames
      value: ["kata", "kata-clh", "kata-qemu"]
  target:
    kind: CcRuntime

