apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -ssh-demo

resources:
- ../base

images:
- name: quay.io/confidential-containers/runtime-payload
  newTag: kata-containers-ssh-demo-v0.2.0
- name: quay.io/confidential-containers/reqs-payload
  newTag: e45d4e84c3ce4ae116f3f4d6c123c4829606026f

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClasses
      value:
      - name: "kata"
        snapshotter: "overlayfs"
      - name: "kata-clh"
        snapshotter: "overlayfs"
      - name: "kata-qemu"
        snapshotter: "overlayfs"
  target:
    kind: CcRuntime

