# permissions for end users to view ccruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccruntime-viewer-role
rules:
- apiGroups:
  - confidentialcontainers.org
  - peerpodconfiguration.confidentialcontainers.org
  resources:
  - ccruntimes
  - peerpodconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - confidentialcontainers.org
  - peerpodconfiguration.confidentialcontainers.org
  resources:
  - ccruntimes/status
  - peerpodconfigs/status
  verbs:
  - get
