apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -sample

resources:
- ../base

images:
- name: quay.io/confidential-containers/container-engine-for-cc-payload
  newTag: c80c3e7392c1562841e75072d227e07f98cab2bd
- name: quay.io/confidential-containers/runtime-payload
  newName: quay.io/confidential-containers/runtime-payload-ci
  newTag: kata-containers-f5420e5cf198eb54585dad9fb63eb2eaaff3e5a8

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClassNames
      value: ["kata", "kata-clh", "kata-clh-tdx", "kata-qemu", "kata-qemu-tdx", "kata-qemu-sev", "kata-qemu-snp"]
  target:
    kind: CcRuntime
