apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -sample

resources:
- ../base

images:
- name: quay.io/confidential-containers/reqs-payload
  newTag: fad6ef4607e929c2d30d16dc8c62fbb29881a44c
- name: quay.io/confidential-containers/runtime-payload
  newName: quay.io/confidential-containers/runtime-payload-ci
  newTag: kata-containers-424de1cbfa4e1da9ecf9a56b1d1e1a11a4f339cd

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClasses
      value:
      - name: "kata-clh"
        snapshotter: "nydus"
      - name: "kata-clh-tdx"
        snapshotter: "nydus"
      - name: "kata-qemu"
        snapshotter: "nydus"
      - name: "kata-qemu-tdx"
        snapshotter: "nydus"
      - name: "kata-qemu-sev"
        snapshotter: "nydus"
      - name: "kata-qemu-snp"
        snapshotter: "nydus"
    - op: add
      path: /spec/config/defaultRuntimeClassName
      value: "kata-qemu"
    - op: add
      path: /spec/config/debug
      value: false
  target:
    kind: CcRuntime
