apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -sample

resources:
- ../base

images:
- name: quay.io/confidential-containers/container-engine-for-cc-payload
  newTag: 7c307c329cb501b7a80fa59f2df138c6c5042e29
- name: quay.io/confidential-containers/runtime-payload
  newName: quay.io/confidential-containers/runtime-payload
  newTag: kata-containers-b91337afef54d94e7f6458a0d1548e921dab6ea0-x86_64

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClassNames
      value: ["kata", "kata-clh", "kata-clh-tdx", "kata-qemu", "kata-qemu-tdx", "kata-qemu-sev"]
  target:
    kind: CcRuntime
