resources:
- ../base

nameSuffix: -sgx-mode-sim

images:
- name: quay.io/confidential-containers/runtime-payload-ci
  newTag: enclave-cc-SIM-sample-kbc-latest
- name: quay.io/confidential-containers/reqs-payload
  newTag: e45d4e84c3ce4ae116f3f4d6c123c4829606026f
