resources:
- ../base

nameSuffix: -sgx-mode-sim

images:
- name: quay.io/confidential-containers/runtime-payload
  newTag: enclave-cc-SIM-sample-kbc-v0.10.0
- name: quay.io/confidential-containers/reqs-payload
  newTag: 12e8fbc72e927f9d684efe2e1214937f8b0544fc
