resources:
- ../base

nameSuffix: -sgx-mode-sim

images:
- name: quay.io/confidential-containers/runtime-payload-ci
  newTag: enclave-cc-SIM-sample-kbc-ed979ef2952d8b20c2f0abee3d32a3617d2c57bb
- name: quay.io/confidential-containers/reqs-payload
  newTag: c31205eb31d8a4623ffc0c9fa316e3c91e337023
