apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

nameSuffix: -sgx-mode-hw

- name: quay.io/confidential-containers/reqs-payload
  newTag: 4ad0978b8e9f1acb857fe2c76f1494c55bf28e05
