apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -peer-pods

resources:
- ../base

images:
- name: quay.io/confidential-containers/reqs-payload
  newTag: latest
- name: quay.io/confidential-containers/runtime-payload
  newName: quay.io/confidential-containers/runtime-payload-ci
  newTag: kata-containers-latest

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClasses
      value:
      - name: "kata-remote"
        snapshotter: "nydus"
    - op: add
      path: /spec/config/debug
      value: false
  target:
    kind: CcRuntime
