name: ccruntime e2e tests
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e:
    name: operator tests
    strategy:
      fail-fast: false
      matrix:
        runtimeclass: ["kata-qemu", "kata-clh"]
        instance: ["az-ubuntu-2004", "az-ubuntu-2204"]
    runs-on: ${{ matrix.instance }}
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible python-is-python3

      - name: Run e2e tests
        timeout-minutes: 45
        run: |
          cd tests/e2e
          export PATH="$PATH:/usr/local/bin"
          ./run-local.sh -r "${{ matrix.runtimeclass }}" -u
