name: enclave-cc e2e tests
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e:
    name: operator enclave-cc install e2e tests
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: localhost:5000/cc-operator:latest

      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/cc-operator:latest
          docker ps

      - name: Setup kind cluster
        run: |
          kind create cluster -n coco-sgx --config tests/e2e/enclave-cc-kind-config.yaml
          kubectl get nodes
