name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4

    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Download controller-gen
      run: make controller-gen

    - name: Download kustomize
      run: make kustomize

    - name: Download envtest
      run: make envtest

    - name: Build controller
      run: make build

    - name: Build bundle
      run: make bundle IMG=quay.io/confidential-containers/operator:latest

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    needs:
      - build
    uses: "./.github/workflows/lib-codeql.yaml"
