name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Set up Go
      uses: actions/setup-go@b26d40294f8ad76fcc90b915dac85892322fe62d # v5
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Download controller-gen
      run: make controller-gen

    - name: Download kustomize
      run: make kustomize

    - name: Download envtest
      run: make envtest

    - name: Build controller
      run: make build

    - name: Build bundle
      run: make bundle IMG=quay.io/confidential-containers/operator:latest

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    needs:
      - build
    uses: "./.github/workflows/lib-codeql.yaml"
